# Generated by Django 2.1.8 on 2019-07-26 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Buyer', '0001_initial'),
        ('Store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='下单时间')),
                ('order_id', models.IntegerField(verbose_name='订单号码')),
                ('number', models.IntegerField(verbose_name='购买产品的数量')),
                ('money', models.IntegerField(verbose_name='花费的钱数')),
                ('buyer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Buyer.Buyer', verbose_name='买家id')),
                ('goods_id', models.ManyToManyField(to='Store.Goods', verbose_name='商品id')),
            ],
        ),
    ]
