# Generated by Django 2.1.8 on 2019-07-27 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buyer', '0001_initial'),
        ('Store', '0002_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='address_id',
            field=models.ManyToManyField(to='Buyer.Address', verbose_name='收货地址id'),
        ),
        migrations.AddField(
            model_name='customer',
            name='order_status',
            field=models.IntegerField(default=1, verbose_name='订单的状态'),
        ),
    ]
