# Generated by Django 2.1.8 on 2019-07-27 03:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Buyer', '0001_initial'),
        ('Store', '0003_auto_20190727_1013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='address_id',
        ),
        migrations.AddField(
            model_name='customer',
            name='address_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Buyer.Address', verbose_name='收货地址id'),
        ),
    ]
