# Generated by Django 2.1.8 on 2019-07-27 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0004_auto_20190727_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='address_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Buyer.Address', verbose_name='收货地址id'),
        ),
    ]
