# Generated by Django 2.1.8 on 2019-07-27 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0005_auto_20190727_1139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='address_id',
        ),
    ]
