# Generated by Django 2.1.8 on 2019-07-27 03:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Buyer', '0001_initial'),
        ('Store', '0006_remove_customer_address_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='address_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Buyer.Address', verbose_name='收货地址id'),
        ),
    ]
