# Generated by Django 2.1.8 on 2019-07-27 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Buyer', '0001_initial'),
        ('Store', '0010_customer_pay_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buycar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='添加商品的数量')),
                ('buyer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Buyer.Buyer', verbose_name='买家id')),
                ('goods_id', models.ManyToManyField(to='Store.Goods', verbose_name='商品id')),
            ],
        ),
    ]
