# Generated by Django 2.1.8 on 2019-07-29 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0011_buycar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buycar',
            name='buyer_id',
        ),
        migrations.RemoveField(
            model_name='buycar',
            name='goods_id',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='address_id',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='buyer_id',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='goods_id',
        ),
        migrations.DeleteModel(
            name='Buycar',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
